# Generated by Django 2.2.6 on 2020-02-10 14:43

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('Book_descroption', models.TextField(max_length=1500)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(default=datetime.date.today)),
            ],
            options={
                'verbose_name_plural': 'Books',
                'verbose_name': 'Book',
                'db_table': 'Books',
            },
        ),
    ]
